name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt install -y texlive-base texlive-latex-extra make git
      - name: Build pdf
        run: make
      - name: Push to GitHub
        # You may pin to the exact commit or the version.
        # uses: markjivko/push-to-github@9a774f8ac00f8b551f9883f51941cff089df57a0
        uses: markjivko/push-to-github@main
        env:
          GITHUB_SSH_KEY: ${{ secrets.GITHUB_PRIVATE_SSH_KEY }}
        with:
          # Source directory from the origin directory
          source-directory: ./artifacts
          # Target repository username
          target-github-username: sohomdatta1
          # Target repository name
          target-github-repository: cv
          # Target repository branch name; defaults to 'main'
          target-github-branch: artifacts
          # Target repository directory
          target-directory: ./artifacts