on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt update && apt install -y texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-full make git
      - name: Build pdf
        run: make
      - name: Push to GitHub
        uses: markjivko/push-to-github@main
        env:
          GITHUB_SSH_KEY: ${{ secrets.CV_GITHUB_PRIVATE_SSH_KEY }}
        with:
          # Source directory from the origin directory
          source-directory: ./artifacts
          # Target repository username
          target-github-username: sohomdatta1
          # Target repository name
          target-github-repository: cv
          # Target repository branch name; defaults to 'main'
          target-github-branch: artifacts
          # Target repository directory
          target-directory: ./artifacts