on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - name: Install texlive
        run: apt update && apt install -y texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-full make git
      - name: Extract short SHA
        id: short_sha
        run: git config --global --add safe.directory /__w/cv/cv && echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build pdf
        run: GIT_HASH=${{ steps.short_sha.outputs.sha_short }} make
      - name: Push to GitHub
        uses: markjivko/push-to-github@main
        env:
          GITHUB_SSH_KEY: ${{ secrets.CV_GITHUB_PRIVATE_SSH_KEY }}
        with:
          # Source directory from the origin directory
          source-directory: ./artifacts
          # Target repository username
          target-github-username: sohomdatta1
          # Target repository name
          target-github-repository: cv
          # Target repository branch name; defaults to 'main'
          target-github-branch: artifacts
          # Target repository directory
          target-directory: ./artifacts
